---
- name: default prerequisite for all hosts.  
  hosts: all
  become: yes
  gather_facts: no
  vars:

  tasks:
  
    - name: DNF update the system
      ansible.builtin.dnf:
        name:  "*"
        state: latest
  
    - name: Install iproute-tc, iperf3, nano, tcpdump and traceroute
      ansible.builtin.dnf:
        name:
          - iproute-tc
          - iperf3
          - nano
          - tcpdump
          - traceroute
        update_cache: yes

- name: default prerequisite for all routers
  hosts: r1, r2, r3, r4, r5
  become: yes
  gather_facts: no
  vars:
  
  tasks:
  
    - name: edit sysctl.conf for ipv4 forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
    
    - name: Install kernel-modules-extra
      ansible.builtin.dnf:
        name:
          - kernel-modules-extra
        update_cache: yes
    
    - name: Reboot required
      ansible.builtin.command: "/usr/bin/needs-restarting -r"
      register: reboot_required
      ignore_errors: True
      changed_when: False
      failed_when: reboot_required.rc == 2
      
    - name: Rebooting
      ansible.builtin.reboot:
        post_reboot_delay: 80
      throttle: 1
      when: reboot_required.rc == 1
    
    - debug:
        var: reboot_required.rc
        verbosity: 2

    - name: Check the uptime post reboot
      ansible.builtin.shell: uptime
      register: UPTIME_POST_REBOOT
      when: reboot_required.rc == 1

    - debug: msg={{UPTIME_POST_REBOOT.stdout}}
      when: reboot_required.rc == 1